# Generated by Django 3.1.13 on 2023-06-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0011_auto_20200919_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='dead_line',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
