# Generated by Django 3.1.13 on 2023-06-16 05:09

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='Ethiopia', max_length=2, null=True),
        ),
    ]
